workflows:
  build_apk:
    name: Build Android APK
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Generate Hive adapters
        script: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
